### ISSUE TITLE
Node just "dies" silently and stops returning any data from the server

### ISSUE THREAD

**Issue by pakerfeldt** [BiancoRoyal/node-red-contrib-modbus#553]
### Which node-red-contrib-modbus version are you using?

5.45.1

### What happened?

I have a weird issue where requests to a specific Modbus TCP device just stops working randomly. Since the way to mitigate the problem is often to just add another node with the same settings, request an address and then delete it again I suspect the issue is somewhere in this library. I have enabled logging `DEBUG=contribModbus*` but it's not logging _anything_ when I request data. It's just silent.

<img width="689" height="97" alt="Image" src="https://github.com/user-attachments/assets/137f4e44-1897-4e30-9359-5fd30524222f" />

<img width="647" height="535" alt="Image" src="https://github.com/user-attachments/assets/63f17960-2091-433f-b43c-d2e3256e8311" />

<img width="638" height="554" alt="Image" src="https://github.com/user-attachments/assets/891b87bc-1cf8-4c7b-8533-5c37b6691da5" />

### Server

Other/External server

### How can this be reproduced?

Unfortunately very hard to give reproduction steps for someone else, but I'd be happy to add more logging if only I knew how.

### What did you expect to happen?

Expect the node to successfully read data from the server, or at the very least, log why it's not working.

### Other Information

I suspect this information from Node-RED log is relevant:
```
2025-11-29T16:59:53.409Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.409Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.405Z contribModbus:queue:core queue serial unlock command node name: SigEnergy id: d187845f8ee14cf5
2025-11-29T16:59:53.406Z contribModbus:queue:core sequential de-queue command
2025-11-29T16:59:53.409Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.409Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.410Z contribModbus:queue:core queue serial lock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.410Z contribModbus:getter Modbus client broken
2025-11-29T16:59:53.410Z contribModbus:basics Modbus client broken
2025-11-29T16:59:53.414Z contribModbus:queue:core queue serial unlock command node name: SigEnergy id: d187845f8ee14cf5
2025-11-29T16:59:53.415Z contribModbus:queue:core sequential de-queue command
2025-11-29T16:59:53.424Z contribModbus:queue:core queue serial unlock command node name: SigEnergy id: d187845f8ee14cf5
2025-11-29T16:59:53.904Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.904Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.904Z contribModbus:getter Port Not Open
2025-11-29T16:59:53.904Z contribModbus:core Message Not Found 692b2689a4c9ce5fdaddcc0d
2025-11-29T16:59:58.415Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T17:00:00.011Z contribModbus:queue:core queue serial lock command node name: VP+Energy id: ec62397f.a914a8
2025-11-29T17:00:00.011Z contribModbus:queue:core queue serial lock command node name: EnergyPool id: d63d534e.9773c
2025-11-29T17:00:00.016Z contribModbus:queue:core sequential de-queue command
2025-11-29T16:59:53.410Z contribModbus:queue:core queue serial lock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.410Z contribModbus:getter Modbus client broken
2025-11-29T16:59:53.410Z contribModbus:basics Modbus client broken
2025-11-29T16:59:53.414Z contribModbus:queue:core queue serial unlock command node name: SigEnergy id: d187845f8ee14cf5
2025-11-29T16:59:53.415Z contribModbus:queue:core sequential de-queue command
2025-11-29T16:59:53.424Z contribModbus:queue:core queue serial unlock command node name: SigEnergy id: d187845f8ee14cf5
2025-11-29T16:59:53.904Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.904Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T16:59:53.904Z contribModbus:getter Port Not Open
2025-11-29T16:59:53.904Z contribModbus:core Message Not Found 692b2689a4c9ce5fdaddcc0d
2025-11-29T16:59:58.415Z contribModbus:queue:core queue serial unlock command node name: SolarEdge id: 7bdef551.8edacc
2025-11-29T17:00:00.011Z contribModbus:queue:core queue serial lock command node name: VP+Energy id: ec62397f.a914a8

```
From this moment on, I didn't see any more entries with `SolarEdge` which is the one failing. So without knowing for sure, I suspect the "Port Not Open" is associated with the failing server. It _could_ be that SolarEdge is responding with something weird, and that this library fails to re-connect.

**Comment by pakerfeldt** [comment]
I'm switching to a flex getter just to see if it changes anything.

**Comment by pakerfeldt** [comment]
Just happened again with the flex getter so that didn't change anything.

**Comment by DmitrySidorow** [comment]
very annoying issue, hope it will be fixed

**Comment by grewek** [comment]
Please update to 5.45.2 the issue might be related to a regression that i accidentally introduced in 5.45.1 if that doesn't change the behavior please let me know.

**Comment by pakerfeldt** [comment]
> Please update to 5.45.2 the issue might be related to a regression that i accidentally introduced in 5.45.1 if that doesn't change the behavior please let me know.

Stable thus far, been running 4-5 hours now 🙏. Will give an update again later.

**Comment by pakerfeldt** [comment]
Still stable, looks like the regression was fixed in 5.45.2. Thank you! ⭐

**Comment by javelinstasca** [comment]
Hello,
After upgrading to version 5.45.2 on Jan 13, 2026, I’m still seeing a random issue where the flex getter node fails to read from the ModbusTCP server. Once it stops reading, it never recovers or triggers again. I had to roll back to 5.43.0, which seems much more stable for now.

Could you recheck at this problem?

**Comment by biancode** [comment]
**v5.46.0 note:** Client FSM/queue hardening in this release targets silent client death (see #564). Not auto-closing — please upgrade to **5.46.0** and reopen or comment if the node still stops returning data without errors.

**Comment by biancode** [comment]
**Follow-up — `node-red-contrib-modbus@5.46.0` is published on npm**

Earlier note: this symptom was a target of the v5.46.0 client FSM / reconnect / queue hardening ([CHANGELOG](https://github.com/BiancoRoyal/node-red-contrib-modbus/blob/master/CHANGELOG.md)).

Please upgrade and field-test:

```bash
npm i node-red-contrib-modbus@5.46.0
```

Then:
- reply here with ✅ **fixed** or ❌ **still broken** (short repro + NR/Node versions), or
- **reopen** this issue, or
- open a **new** issue if you see a different regression

We treat reporter confirmation as the real close criterion — thank you.
